name = "hartland-country-house"
main = "server.js" 
compatibility_date = "2024-02-25"

account_id = "1b80d9c0b3db364c41a57489888eeeeb"
workers_dev = true

[build]
command = "npm install"
upload.dir = "public"

[dev]
port = 8787

[env.production]
route = "hartlandcountryhouse.co.za/*"
zone_id = "de7d1eba501552a48069752add3ef9cb"
